ClubDeSocios/Models/Socio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Web;

namespace ClubDeSocios.Models
{

    public enum Sexo{M, F}

    public class Socio
    {
        [Key]
        public int SocioID { get; set; }

        [Required]
        [Display(Name ="Nombre del socio")]
        public string Nombre { get; set; }

        [Required]
        [Display(Name = "Apellido del socio")]
        public string Apellidos { get; set; }

        [Required]
        [Display(Name = "Cédula")]
        public string Cedula { get; set; }

        [DataType(DataType.Upload)]
        [Display(Name = "Foto")]
        public byte[] Foto { get; set; }

        [Required]
        [Display(Name = "Dirección")]
        public string Direccion { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Teléfono/Celular/Fax")]
        public string TelefonoCelularFax { get; set; }

        [Required]
        [Display(Name = "Sexo")]
        public Sexo Sexo { get; set; }

        [Required]
        [Display(Name = "Edad")]
        public int Edad { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Nacimiento")]
        public DateTime FechaNacimiento { get; set; }

        [Required]
        [Display(Name = "Tipo de Membresía")]
        public string TipoMembresia { get; set; }

        [Required]
        [Display(Name = "Lugar de Trabajo")]
        public string LugarTrabajo { get; set; }

        [Required]
        [Display(Name = "Dirección de Oficina")]
        public string DireccionOficina { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Teléfono de Oficina")]
        public string TelefonoOficina { get; set; }

        [Required]
        [Display(Name = "Estado de Membresía")]
        public bool EstadoMembresia { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Ingreso")]
        public DateTime FechaIngreso { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Salida")]
        public DateTime FechaSalida { get; set; }


    }
}

ClubDeSocios/Controllers/SociosController.cs
using ClubDeSocios.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ClubDeSocios.Controllers
{
    public class SociosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Socios
        public ActionResult Index(int? id)
        {
            if (id==null)
            {
                return View(db.Socios.ToList());
            }
            return View(db.Socios.ToList().Where(s=>s.SocioID == id));
        }

        // GET: Socios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Socio socio = db.Socios.Find(id);
            if (socio == null)
            {
                return HttpNotFound();
            }
            return View(socio);
        }

        // GET: Socios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Socios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SocioID,Nombre,Apellidos,Cedula,Foto,Direccion,TelefonoCelularFax,Sexo,Edad,FechaNacimiento,TipoMembresia,LugarTrabajo,DireccionOficina,TelefonoOficina,EstadoMembresia,FechaIngreso,FechaSalida")] Socio socio, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    if (upload.FileName.EndsWith(".jpg"))
                    {
                        using (MemoryStream memoryStream = new MemoryStream())
                        {
                            upload.InputStream.CopyTo(memoryStream);
                            byte[] arreglo = memoryStream.GetBuffer();
                            socio.Foto = arreglo;
                            db.Socios.Add(socio);
                            db.SaveChanges();
                            return RedirectToAction("Index");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("Foto", "Es necesario que la imagen tenga formato JPG");
                    }

                }
                else
                {
                    ModelState.AddModelError("Foto", "Es necesario seleccionar una imagen");
                }

            }

            return View(socio);
        }

        // GET: Socios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Socio socio = db.Socios.Find(id);
            if (socio == null)
            {
                return HttpNotFound();
            }
            return View(socio);
        }

        // POST: Socios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SocioID,Nombre,Apellidos,Cedula,Foto,Direccion,TelefonoCelularFax,Sexo,Edad,FechaNacimiento,TipoMembresia,LugarTrabajo,DireccionOficina,TelefonoOficina,EstadoMembresia,FechaIngreso,FechaSalida")] Socio socio, HttpPostedFileBase upload)
        {

            if (ModelState.IsValid)
            {
                Socio _socio = new Socio();
                if (upload != null && upload.ContentLength > 0)
                {
                    if (upload.FileName.EndsWith(".jpg"))
                    {
                        using (MemoryStream memoryStream = new MemoryStream())
                        {
                            upload.InputStream.CopyTo(memoryStream);
                            byte[] arreglo = memoryStream.GetBuffer();
                            socio.Foto = arreglo;
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("Foto", "Es necesario que la imagen tenga formato JPG");
                        return View(socio);
                    }

                }
                else
                {
                    _socio = db.Socios.Find(socio.SocioID);
                    socio.Foto = _socio.Foto;
                }
                db.Entry(_socio).State = EntityState.Detached;
                db.Entry(socio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(socio);
        }

        // GET: Socios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Socio socio = db.Socios.Find(id);
            if (socio == null)
            {
                return HttpNotFound();
            }
            return View(socio);
        }

        // POST: Socios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Socio socio = db.Socios.Find(id);
            db.Socios.Remove(socio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult obtenerImagen(int id)
        {
            Socio socio = db.Socios.Find(id);
            byte[] byteImagen = socio.Foto;

            MemoryStream memoryStream = new MemoryStream(byteImagen);
            Image image = Image.FromStream(memoryStream);

            memoryStream = new MemoryStream();
            image.Save(memoryStream, ImageFormat.Jpeg);
            memoryStream.Position = 0;

            return File(memoryStream,"image/jpg");
        }
    }
}

ClubDeSocios/Views/Socios/Create.cshtml
@model ClubDeSocios.Models.Socio

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Socios", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Socio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Foto", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="foto" name="upload" />
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelefonoCelularFax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelefonoCelularFax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelefonoCelularFax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Sexo, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoMembresia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoMembresia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoMembresia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LugarTrabajo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LugarTrabajo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LugarTrabajo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DireccionOficina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DireccionOficina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DireccionOficina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelefonoOficina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelefonoOficina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelefonoOficina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstadoMembresia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EstadoMembresia)
                    @Html.ValidationMessageFor(model => model.EstadoMembresia, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaIngreso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaIngreso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaIngreso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaSalida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaSalida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaSalida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClubDeSocios/Views/Socios/Delete.cshtml
@model ClubDeSocios.Models.Socio

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Socio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            <img width="100" src="@Url.Action("obtenerImagen", "Socios", new { id = Model.SocioID})" alt="Alternate Text" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelefonoCelularFax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelefonoCelularFax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoMembresia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoMembresia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LugarTrabajo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LugarTrabajo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DireccionOficina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DireccionOficina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelefonoOficina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelefonoOficina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoMembresia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoMembresia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaSalida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaSalida)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ClubDeSocios/Views/Socios/Details.cshtml
@model ClubDeSocios.Models.Socio

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Socio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            <img width="100" src="@Url.Action("obtenerImagen", "Socios", new { id = Model.SocioID})" alt="Alternate Text" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelefonoCelularFax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelefonoCelularFax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoMembresia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoMembresia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LugarTrabajo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LugarTrabajo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DireccionOficina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DireccionOficina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelefonoOficina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelefonoOficina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoMembresia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoMembresia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaSalida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaSalida)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SocioID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ClubDeSocios/Views/Socios/Index.cshtml
@model IEnumerable<ClubDeSocios.Models.Socio>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellidos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cedula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TelefonoCelularFax)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sexo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Edad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoMembresia)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellidos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cedula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TelefonoCelularFax)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sexo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Edad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaNacimiento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoMembresia)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.SocioID }) |
            @Html.ActionLink("Details", "Details", new { id=item.SocioID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.SocioID })
        </td>
    </tr>
}

</table>